// =============================================================================
// SOLANA NFT COLLECTION TUTORIAL
// =============================================================================
// 📚 BEFORE RUNNING: Read the README.md file for concept explanations
// 🎯 PURPOSE: Create your first NFT collection on Solana devnet
// ⏱️ DURATION: ~10 seconds to run
// 💰 COST: Free on devnet (uses test SOL)
//
// QUICK START:
// 1. Ensure you have a Solana keypair: solana-keygen new
// 2. Install dependencies: npm install
// 3. Run this script: npx esrun create-collection.ts
// 4. Check output for your collection's Explorer link
//
// WHAT THIS SCRIPT DOES:
// ✓ Connects to Solana devnet
// ✓ Loads your wallet from ~/.config/solana/id.json
// ✓ Requests devnet SOL if needed
// ✓ Generates a new mint account for the collection
// ✓ Creates NFT collection with metadata
// ✓ Verifies creation succeeded
//
// OUTPUT: A collection NFT address you can view on Solana Explorer
//
// KEY CONCEPTS (refer to README for details):
// - Mint Account: The NFT's unique identity/address (generated by this script)
// - Your Wallet: Pays fees and owns the NFT token
// - Token Metadata Program: Stores NFT data on-chain
// - Umi: Modern SDK that simplifies Metaplex interactions
// =============================================================================

import { createNft, fetchDigitalAsset, mplTokenMetadata } from "@metaplex-foundation/mpl-token-metadata";

import { airdropIfRequired, getExplorerLink, getKeypairFromFile } from "@solana-developers/helpers";

import { generateSigner, keypairIdentity, percentAmount } from "@metaplex-foundation/umi";
import { createUmi } from "@metaplex-foundation/umi-bundle-defaults";

import { clusterApiUrl, Connection, LAMPORTS_PER_SOL, PublicKey } from "@solana/web3.js";

// =============================================================================
// STEP 1: CONNECT TO SOLANA DEVNET
// =============================================================================
// Creates a connection to Solana's devnet (free test network)
// - devnet = test network with free tokens (what we use for learning)
// - testnet = more stable test network
// - mainnet-beta = production network with real SOL (costs real money!)
//
// "confirmed" commitment level = wait for network confirmation before proceeding
const connection = new Connection(clusterApiUrl("devnet"), "confirmed");

// =============================================================================
// STEP 2: LOAD YOUR WALLET
// =============================================================================
// Loads your Solana keypair from ~/.config/solana/id.json
// This is the DEFAULT location created by: solana-keygen new
//
// IMPORTANT: This is YOUR wallet that will:
// - Pay transaction fees (small amount of SOL)
// - Sign the transaction to authorize it
// - Receive/own the collection NFT token
//
// NOT TO BE CONFUSED WITH: The mint account (created later in STEP 5)
const user = await getKeypairFromFile();

// =============================================================================
// STEP 3: REQUEST DEVNET SOL (FREE TEST TOKENS)
// =============================================================================
// Checks if wallet has at least 0.5 SOL. If not, requests 1 SOL airdrop.
// 
// DEVNET ONLY: This gives you free test SOL for development
// - Devnet SOL has NO real-world value
// - Rate limited: ~5 SOL per hour per IP address
// - Alternative: https://faucet.solana.com if this fails
//
// ON MAINNET: Remove this! Airdrops don't exist. You must purchase SOL.
//
// COMMON MISTAKE: Trying to airdrop on mainnet will fail
try {
    await airdropIfRequired(connection, user.publicKey, 1 * LAMPORTS_PER_SOL, 0.5 * LAMPORTS_PER_SOL);
} catch (error) {
    console.log("Airdrop failed (you may already have sufficient balance):", error.message);
}

console.log("Loaded user:", user.publicKey.toBase58());

// =============================================================================
// STEP 4: INITIALIZE UMI FRAMEWORK
// =============================================================================
// Umi is Metaplex's modern framework for building Solana apps
// Think of it as a "toolbox" that provides pre-built functions for NFTs
//
// WHY UMI?
// - Simplifies complex Token Metadata interactions
// - Plugin-based: Add features as you need them
// - Type-safe: Catches errors before runtime
// - Maintained by Metaplex: Always up-to-date with standards
//
// This creates the Umi instance configured for devnet
const umi = createUmi(connection.rpcEndpoint);

// Load the Token Metadata plugin
// WITHOUT THIS: Umi doesn't know how to create NFTs
// WITH THIS: Umi gains functions like createNft(), fetchDigitalAsset(), etc.
//
// The Token Metadata Program is a smart contract on Solana that stores NFT data
// This plugin teaches Umi how to interact with that program
umi.use(mplTokenMetadata())

// Convert web3.js keypair format to Umi's internal format
// WHY NEEDED: web3.js and Umi use different keypair structures internally
// - web3.js: Uses Keypair class from @solana/web3.js
// - Umi: Uses its own keypair format for consistency across Metaplex tools
//
// user.secretKey contains both public and private key (64 bytes total)
const umiUser = umi.eddsa.createKeypairFromSecretKey(user.secretKey);

// Tell Umi which wallet will sign transactions
// This sets the "identity" - the wallet that authorizes all operations
// 
// WHAT THIS DOES:
// - All transactions will be signed by this wallet
// - Transaction fees will be paid from this wallet
// - This wallet becomes the "update authority" for the collection
//   (meaning it can modify collection metadata later)
//
// SECURITY NOTE: Never share this private key. On mainnet, use hardware wallets.
umi.use(keypairIdentity(umiUser));

console.log("Set up Umi instance for user:", umiUser.publicKey);

// =============================================================================
// STEP 5: GENERATE THE MINT ACCOUNT (MOST IMPORTANT CONCEPT!)
// =============================================================================
// THIS IS THE MOST CONFUSING PART FOR BEGINNERS - READ CAREFULLY!
//
// What is a Mint Account?
// - A SEPARATE account from your wallet that represents the NFT itself
// - Think: ISBN for a book, VIN for a car, SKU for a product
// - This becomes the NFT's permanent, globally unique address
//
// Key Insight: TWO DIFFERENT KEYPAIRS/ADDRESSES
// 
// 1. YOUR WALLET (user):
//    - Example: 8Q4gyVRn...TizGgCh
//    - Purpose: Pay fees, sign transactions, OWN tokens
//    - You control this with your private key
//    - Loaded from: ~/.config/solana/id.json
//
// 2. MINT ACCOUNT (collectionMint) - GENERATED HERE:
//    - Example: FTwh5Nhh...bHV17R
//    - Purpose: The NFT's unique identity/definition
//    - After creation, owned by Token Metadata Program (not you directly!)
//    - Generated: Fresh random keypair EVERY time this script runs
//
// Why Generate a New Random Keypair?
// 1. UNIQUENESS: Every NFT needs a globally unique address on Solana
// 2. SEPARATION: Mint stores NFT definition; your wallet proves ownership
// 3. ONE-TIME USE: Private key signs creation tx, then typically discarded
//
// What Happens to the Keys?
// - Private Key: Used ONCE to sign the creation transaction, then forgotten
// - Public Key: Becomes the permanent address everyone uses to reference the NFT
//
// Visual:
//     generateSigner()
//           ↓
//     ┌──────────────────────┐
//     │ NEW Random Keypair   │
//     ├──────────────────────┤
//     │ Private Key (64B)    │ → Used once, then discarded
//     │ Public Key (32B)     │ → Becomes NFT address: FTwh5N...bHV17R
//     └──────────────────────┘
//
// COMMON MISTAKE: Thinking this is your wallet. It's not!
// This is the NFT's address. Your wallet will HOLD this NFT.
const collectionMint = generateSigner(umi);

// =============================================================================
// STEP 6: CREATE THE NFT COLLECTION
// =============================================================================
// This builds a transaction to create the NFT collection on-chain
//
// PARAMETERS EXPLAINED:
//
// mint: collectionMint
//   - The NEW unique address for this collection (from Step 5)
//   - This becomes the collection's permanent on-chain identifier
//   - Example output: FTwh5NhhjgsPnqgMFhusxuZYJWrZaaSLz4ohvGbHV17R
//
// name: "Radu's Collection"
//   - Human-readable name (max 32 characters)
//   - Displayed in wallets and marketplaces
//   - Can include emojis: "🚀 Space NFTs"
//
// symbol: "RCOL"
//   - Short ticker symbol (max 10 characters)
//   - Like stock tickers: AAPL, TSLA, etc.
//   - Used in compact displays
//
// uri: "https://raw.githubusercontent.com/..."
//   - Points to OFF-CHAIN metadata JSON file
//   - CRITICAL: This JSON contains the actual NFT description and image URL
//   - Must follow Metaplex metadata standard (see sample-nft-collection-offchain-data.json)
//   - Best practice: Use IPFS or Arweave for permanent, decentralized storage
//   - WARNING: If this URL goes down, the NFT metadata becomes inaccessible!
//
// sellerFeeBasisPoints: percentAmount(0)
//   - Royalty percentage on secondary sales
//   - Basis points: 100 = 1%, 500 = 5%, 1000 = 10%
//   - Example: Set to 500 = you earn 5% every time someone resells this NFT
//   - Set to 0 here = no royalties
//
// isCollection: true
//   - Marks this NFT as a COLLECTION (parent/container)
//   - Allows other NFTs to reference this as their parent
//   - If false, it would be a regular standalone NFT
//   - Collections provide branding and grouping for related NFTs
//
// WHAT HAPPENS UNDER THE HOOD:
// 1. Creates a Mint Account (the token definition)
// 2. Creates a Metadata Account (stores name, symbol, URI)
// 3. Creates a Token Account in your wallet (gives you 1 token = ownership)
// 4. Sets you as the "update authority" (you can modify metadata later)
const transaction = createNft(umi, {
    mint: collectionMint,
    name: "Radu's Collection",
    symbol: "RCOL",
    uri: "https://raw.githubusercontent.com/radufiser/solana_nft/main/sample-nft-collection-offchain-data.json",
    sellerFeeBasisPoints: percentAmount(0),
    isCollection: true,
});

console.log("Creating NFT collection...");
console.log("Collection address:", collectionMint.publicKey);

// =============================================================================
// STEP 7: SEND TRANSACTION TO BLOCKCHAIN
// =============================================================================
// This submits the transaction to Solana and waits for confirmation
//
// sendAndConfirm() does TWO things:
// 1. SEND: Broadcasts the transaction to the network
// 2. CONFIRM: Waits for the transaction to be included in a block
//
// COMMITMENT LEVELS (how "final" is the transaction?):
// - processed: Transaction executed, might be rolled back (FASTEST, RISKY)
// - confirmed: Confirmed by cluster, unlikely to roll back (BALANCED)
// - finalized: Maximum confirmation, cannot roll back (SLOWEST, SAFEST)
//
// WHY USE 'finalized'?
// - Ensures the accounts are FULLY created before we try to fetch them
// - Prevents "account not found" errors in the next step
// - Critical for account creation (less critical for transfers)
// - Trade-off: Adds ~1-2 seconds of wait time for safety
//
// WHAT THIS TRANSACTION DOES:
// 1. Creates the mint account at collectionMint.publicKey
// 2. Initializes it with name, symbol, URI
// 3. Creates metadata account (linked to mint)
// 4. Mints 1 token to your wallet (proves you own the collection)
// 5. Deducts small transaction fee from your wallet (~0.001 SOL)
const result = await transaction.sendAndConfirm(umi, {
    send: { commitment: 'finalized' },
    confirm: { commitment: 'finalized' }
});

console.log("Transaction confirmed:", result.signature);

// =============================================================================
// STEP 8: WAIT FOR RPC INDEXING (IMPORTANT!)
// =============================================================================
// Why this delay?
// - The transaction is confirmed on-chain (Step 7)
// - BUT: RPC nodes need time to INDEX the new account data
// - Without this delay: fetchDigitalAsset() might fail with "account not found"
//
// Technical details:
// - Solana validators confirm blocks every ~400ms
// - RPC nodes query validators and cache results
// - Cache updates take 1-2 seconds to propagate
//
// COMMON MISTAKE: Fetching immediately after creation
// SOLUTION: Wait 2 seconds OR implement retry logic
await new Promise(resolve => setTimeout(resolve, 2000));

// =============================================================================
// STEP 9: VERIFY CREATION BY FETCHING THE NFT
// =============================================================================
// Fetches the created NFT from the blockchain to verify success
//
// What fetchDigitalAsset() returns:
// - mint: The mint account data (address, supply, decimals)
// - metadata: The metadata account data (name, symbol, URI)
// - edition: Edition information (master edition vs print)
//
// This proves the NFT exists on-chain and all accounts were created correctly
const collectionNft = await fetchDigitalAsset(
    umi,
    collectionMint.publicKey
);

// =============================================================================
// SUCCESS! COLLECTION CREATED
// =============================================================================
// Print the Solana Explorer link where you can view your collection
//
// What to check on the Explorer:
// 1. Metadata tab: Verify name, symbol, URI
// 2. Token Accounts: See your wallet owns 1 token (the collection NFT)
// 3. Holders: Confirms you're the sole holder
// 4. Metadata JSON: Click the URI to view off-chain metadata
//
// THE NFT ADDRESS: collectionNft.mint.publicKey
// - This is the permanent, unique identifier for your collection
// - Use this address to:
//   • Mint individual NFTs into this collection
//   • Reference the collection in marketplaces
//   • Query collection metadata
//   • Transfer collection ownership
//
// CONGRATULATIONS! You've created your first NFT collection on Solana!
// 
// NEXT STEPS (see README):
// 1. Mint individual NFTs that belong to this collection
// 2. Upload metadata to IPFS/Arweave for decentralization
// 3. Set up royalties for secondary sales
// 4. Build a minting UI for your users
console.log(`Collection created for address: ${getExplorerLink("address", collectionNft.mint.publicKey, "devnet")}`);